name: Build LaTeX document

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: release tag name
        required: false
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_system_packages: |
            unzip
            wget
            curl
            coreutils
            nodejs
            npm
            imagemagick
            libwebp
            librsvg
            git
            py3-pygments
          pre_compile: |
            wget -q "https://github.com/stipub/stixfonts/raw/73d7c426993abacea44288aded4e81b568d57ed1/zipfiles/STIXv2.0.2.zip" -O stix.zip
            unzip -q stix.zip
            wget -q "https://github.com/adobe-fonts/source-han-super-otc/releases/download/20190603/SourceHan.ttc"
            git clone https://github.com/alif-type/xits
            cp xits/*.otf /usr/share/fonts
            git clone https://github.com/dolbydu/font.git
            cp font/unicode/* /usr/share/fonts
            wget -q "http://mirrors.ctan.org/fonts/cm-unicode.zip"
            unzip ./cm-unicode.zip
            cp cm-unicode/fonts/otf/* /usr/share/fonts
            cp STIXv2.0.2/OTF/* /usr/share/fonts
            cp *.ttc /usr/share/fonts
            fc-cache

            cd oi-wiki-export
            npm i
            git clone https://github.com/OI-wiki/OI-wiki.git
            node index.js ./OI-wiki

          root_file: |
            oi-wiki-export.tex
      - name: create tag
        id: create_tag
        run: |
          tag_name=$(TZ="Asia/Shanghai" date +"v%Y%m%d_%H%M")
          if [[ -n "${{github.event.inputs.tag_name}}" ]]; then tag_name=${{github.event.inputs.tag_name}}; fi
          git tag $tag_name
          git push --tags
          echo "::set-output name=tag_name::$tag_name"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: Release ${{ steps.create_tag.outputs.tag_name }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./oi-wiki-export/oi-wiki-export.pdf
          asset_name: OI-wiki.pdf
          asset_content_type: application/pdf
